name: CI

on:
  push:
    branches: [main, dev, Victoria]
  pull_request:
    branches: [main, dev, Victoria]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run Expo build (just checks)
        run: npx expo prebuild --no-install

      # Om du har tester kan du köra dem här, t.ex.
      # - name: Run tests
      #   run: npm test
